
import java.text.MessageFormat;
import javax.swing.table.DefaultTableModel;
import java.text.NumberFormat;
import java.util.Locale;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Adams
 */
public class JavaSaleAssist extends javax.swing.JFrame {

    /**
     * Creates new form JavaSaleAssist
     */
    public JavaSaleAssist() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    //===================Function Declaration=======================
    
    public void itemCost(){
     double sum = 0;
     for (int i = 0 ; i < jTable1.getRowCount(); i++){
         sum = sum + Double.parseDouble(jTable1.getValueAt(i, 2).toString()); 
     }
     txt_subtotal.setText(Double.toString(sum));
     double cTotal = Double.parseDouble(txt_subtotal.getText());
     
     double cTax = (cTotal * 3.9)/100;
     
     //String itaxtotal = String.format("f %.2f", cTax);
     // Create a NumberFormat instance for the desired locale (e.g., Locale.US for US dollars)
     NumberFormat currencyFormat = NumberFormat.getCurrencyInstance(Locale.GERMANY);

    // Format the cTax value as a currency string
     String formattedTax = currencyFormat.format(cTax);
     txt_tax.setText(formattedTax);  
     
     //String isubtotal = String.format("f %.2f", cTotal);
     NumberFormat currencyFormatSubtotal = NumberFormat.getCurrencyInstance(Locale.GERMANY);

    // Format the cTax value as a currency string
     String formattedSubTotal = currencyFormatSubtotal.format(cTotal);
     
     txt_subtotal.setText(formattedSubTotal);
     
     //String iTotal = String.format("f %.2f", cTotal+cTax);
     NumberFormat currencyFormatSum = NumberFormat.getCurrencyInstance(Locale.GERMANY);

    // Format the cTax value as a currency string
     String formatedSum = currencyFormatSum.format(cTotal+cTax);
     txt_total.setText(formatedSum);
     txt_vat.setText(formattedTax);
     txt_totalreciept.setText(formatedSum);
     
     String Barcode = String.format("f %.2f", cTotal+cTax);
    // txt_barcode.setText(Barcode);
     
    
    }
    //============================function for change======================
    public void Change(){
    double sum = 0;
    double tax = 3.9;
    double cash = Double.parseDouble(txt_cash.getText());
    
    for(int i = 0; i<jTable1.getRowCount(); i++){
    sum = sum + Double.parseDouble(jTable1.getValueAt(i, 2).toString());
    }
    
    double  cTax = (sum * 3.9)/100;
    double cChange = (cash - (sum+cTax));
    //String changegiven = String.format("f %.2f", cChange);
    NumberFormat currencyFormatChange = NumberFormat.getCurrencyInstance(Locale.GERMANY);

    // Format the cTax value as a currency string
     String formatedChange = currencyFormatChange.format(cChange);
    txt_change.setText(formatedChange);
    
    }
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btn_jollof = new javax.swing.JButton();
        btn_cola = new javax.swing.JButton();
        btn_abacha = new javax.swing.JButton();
        btn_burger2 = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jButton49 = new javax.swing.JButton();
        jButton50 = new javax.swing.JButton();
        jButton51 = new javax.swing.JButton();
        jButton52 = new javax.swing.JButton();
        btn_banana = new javax.swing.JButton();
        btn_pizzameat = new javax.swing.JButton();
        btn_apple = new javax.swing.JButton();
        btn_meatpie = new javax.swing.JButton();
        btn_burger = new javax.swing.JButton();
        btn_pepsi = new javax.swing.JButton();
        btn_pizzaleave = new javax.swing.JButton();
        btn_strawberry = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        btn9 = new javax.swing.JButton();
        btn7 = new javax.swing.JButton();
        btn8 = new javax.swing.JButton();
        btn6 = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        btn5 = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        btn1 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btn_clear = new javax.swing.JButton();
        btnzero = new javax.swing.JButton();
        btn_point = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txt_cash = new javax.swing.JTextField();
        txt_change = new javax.swing.JTextField();
        payment_method = new javax.swing.JComboBox<>();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_total = new javax.swing.JTextField();
        txt_subtotal = new javax.swing.JTextField();
        txt_tax = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        btn_remove = new javax.swing.JButton();
        btn_pay = new javax.swing.JButton();
        btn_reset = new javax.swing.JButton();
        btn_exit = new javax.swing.JButton();
        btn_print = new javax.swing.JButton();
        txt_totalreciept = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txt_vat = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SalesAssist");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_jollof.setIcon(new javax.swing.ImageIcon("C:\\Users\\Adams\\Desktop\\Projects\\30_dayscoding_challenge\\JavaPOSApp\\src\\main\\java\\images\\image8.jpg")); // NOI18N
        btn_jollof.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_jollofActionPerformed(evt);
            }
        });
        jPanel1.add(btn_jollof, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 120, 130));

        btn_cola.setIcon(new javax.swing.ImageIcon("C:\\Users\\Adams\\Desktop\\Projects\\30_dayscoding_challenge\\JavaPOSApp\\src\\main\\java\\images\\image10.jpeg")); // NOI18N
        btn_cola.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_colaActionPerformed(evt);
            }
        });
        jPanel1.add(btn_cola, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 290, 110, 130));

        btn_abacha.setIcon(new javax.swing.ImageIcon("C:\\Users\\Adams\\Desktop\\Projects\\30_dayscoding_challenge\\JavaPOSApp\\src\\main\\java\\images\\image9.jpg")); // NOI18N
        btn_abacha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_abachaActionPerformed(evt);
            }
        });
        jPanel1.add(btn_abacha, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 290, 110, 130));

        btn_burger2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Adams\\Desktop\\Projects\\30_dayscoding_challenge\\JavaPOSApp\\src\\main\\java\\images\\image11.jpg")); // NOI18N
        btn_burger2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_burger2ActionPerformed(evt);
            }
        });
        jPanel1.add(btn_burger2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 290, 110, 130));

        jPanel7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel7.add(jButton49, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 120, 130));
        jPanel7.add(jButton50, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 270, 110, 130));
        jPanel7.add(jButton51, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 270, 110, 130));
        jPanel7.add(jButton52, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 270, 110, 130));

        jPanel1.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 10, 610, 420));

        btn_banana.setIcon(new javax.swing.ImageIcon("C:\\Users\\Adams\\Desktop\\Projects\\30_dayscoding_challenge\\JavaPOSApp\\src\\main\\java\\images\\image5.jpeg")); // NOI18N
        btn_banana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_bananaActionPerformed(evt);
            }
        });
        jPanel1.add(btn_banana, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 120, 130));

        btn_pizzameat.setIcon(new javax.swing.ImageIcon("C:\\Users\\Adams\\Desktop\\Projects\\30_dayscoding_challenge\\JavaPOSApp\\src\\main\\java\\images\\image6.jpg")); // NOI18N
        btn_pizzameat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_pizzameatActionPerformed(evt);
            }
        });
        jPanel1.add(btn_pizzameat, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, 110, 130));

        btn_apple.setIcon(new javax.swing.ImageIcon("C:\\Users\\Adams\\Desktop\\Projects\\30_dayscoding_challenge\\JavaPOSApp\\src\\main\\java\\images\\image2.jpg")); // NOI18N
        btn_apple.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_appleActionPerformed(evt);
            }
        });
        jPanel1.add(btn_apple, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 150, 110, 130));

        btn_meatpie.setIcon(new javax.swing.ImageIcon("C:\\Users\\Adams\\Desktop\\Projects\\30_dayscoding_challenge\\JavaPOSApp\\src\\main\\java\\images\\image7.jpeg")); // NOI18N
        btn_meatpie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_meatpieActionPerformed(evt);
            }
        });
        jPanel1.add(btn_meatpie, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 150, 110, 130));

        btn_burger.setIcon(new javax.swing.ImageIcon("C:\\Users\\Adams\\Desktop\\Projects\\30_dayscoding_challenge\\JavaPOSApp\\src\\main\\java\\images\\image11.jpg")); // NOI18N
        btn_burger.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_burgerActionPerformed(evt);
            }
        });
        jPanel1.add(btn_burger, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 120, 130));

        btn_pepsi.setIcon(new javax.swing.ImageIcon("C:\\Users\\Adams\\Desktop\\Projects\\30_dayscoding_challenge\\JavaPOSApp\\src\\main\\java\\images\\image12.jpeg")); // NOI18N
        btn_pepsi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_pepsiActionPerformed(evt);
            }
        });
        jPanel1.add(btn_pepsi, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, 110, 130));

        btn_pizzaleave.setIcon(new javax.swing.ImageIcon("C:\\Users\\Adams\\Desktop\\Projects\\30_dayscoding_challenge\\JavaPOSApp\\src\\main\\java\\images\\image3.jpeg")); // NOI18N
        btn_pizzaleave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_pizzaleaveActionPerformed(evt);
            }
        });
        jPanel1.add(btn_pizzaleave, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 10, 110, 130));

        btn_strawberry.setIcon(new javax.swing.ImageIcon("C:\\Users\\Adams\\Desktop\\Projects\\30_dayscoding_challenge\\JavaPOSApp\\src\\main\\java\\images\\image4.jpeg")); // NOI18N
        btn_strawberry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_strawberryActionPerformed(evt);
            }
        });
        jPanel1.add(btn_strawberry, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 10, 110, 130));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 10, 610, 420));

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn9.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        btn9.setText("9");
        btn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn9ActionPerformed(evt);
            }
        });
        jPanel2.add(btn9, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 40, 90, 70));

        btn7.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        btn7.setText("7");
        btn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn7ActionPerformed(evt);
            }
        });
        jPanel2.add(btn7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 90, 70));

        btn8.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        btn8.setText("8");
        btn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn8ActionPerformed(evt);
            }
        });
        jPanel2.add(btn8, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, 90, 70));

        btn6.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        btn6.setText("6");
        btn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn6ActionPerformed(evt);
            }
        });
        jPanel2.add(btn6, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 130, 90, 70));

        btn4.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        btn4.setText("4");
        btn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn4ActionPerformed(evt);
            }
        });
        jPanel2.add(btn4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 90, 70));

        btn5.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        btn5.setText("5");
        btn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn5ActionPerformed(evt);
            }
        });
        jPanel2.add(btn5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, 90, 70));

        btn3.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        btn3.setText("3");
        btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3ActionPerformed(evt);
            }
        });
        jPanel2.add(btn3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 230, 90, 70));

        btn1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        btn1.setText("1");
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });
        jPanel2.add(btn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 90, 70));

        btn2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        btn2.setText("2");
        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2ActionPerformed(evt);
            }
        });
        jPanel2.add(btn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 230, 90, 70));

        btn_clear.setBackground(new java.awt.Color(255, 0, 0));
        btn_clear.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        btn_clear.setText("C");
        btn_clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_clearActionPerformed(evt);
            }
        });
        jPanel2.add(btn_clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 330, 90, 70));

        btnzero.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        btnzero.setText("0");
        btnzero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnzeroActionPerformed(evt);
            }
        });
        jPanel2.add(btnzero, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, 90, 70));

        btn_point.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        btn_point.setText(".");
        btn_point.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_pointActionPerformed(evt);
            }
        });
        jPanel2.add(btn_point, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 330, 90, 70));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 350, 420));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item", "Quantity", "Amount"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 10, 280, 360));

        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Segoe Print", 1, 24)); // NOI18N
        jLabel4.setText("Cash");
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 118, -1));

        jLabel5.setFont(new java.awt.Font("Segoe Print", 1, 24)); // NOI18N
        jLabel5.setText("Change");
        jPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 118, -1));

        jLabel6.setFont(new java.awt.Font("Segoe Print", 1, 24)); // NOI18N
        jLabel6.setText("Payment Method");
        jPanel4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 210, -1));

        txt_cash.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_cash.setText(" ");
        jPanel4.add(txt_cash, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 60, 230, 30));

        txt_change.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_change.setText(" ");
        jPanel4.add(txt_change, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, 230, 30));

        payment_method.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        payment_method.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cash", "Verve Card", "Master Card", " " }));
        payment_method.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                payment_methodActionPerformed(evt);
            }
        });
        jPanel4.add(payment_method, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 20, 130, -1));

        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 40, 400, 200));

        jPanel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe Print", 1, 24)); // NOI18N
        jLabel1.setText("Tax");
        jPanel5.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 118, -1));

        jLabel2.setFont(new java.awt.Font("Segoe Print", 1, 24)); // NOI18N
        jLabel2.setText("Total");
        jPanel5.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 118, -1));

        jLabel3.setFont(new java.awt.Font("Segoe Print", 1, 24)); // NOI18N
        jLabel3.setText("SubTotal");
        jPanel5.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 118, -1));

        txt_total.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_total.setText(" ");
        jPanel5.add(txt_total, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, 220, 30));

        txt_subtotal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_subtotal.setText(" ");
        jPanel5.add(txt_subtotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, 220, 30));

        txt_tax.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_tax.setText(" ");
        jPanel5.add(txt_tax, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, 220, 30));

        jPanel3.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 400, 200));

        jPanel6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_remove.setFont(new java.awt.Font("Segoe Print", 1, 24)); // NOI18N
        btn_remove.setText("Remove");
        btn_remove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_removeActionPerformed(evt);
            }
        });
        jPanel6.add(btn_remove, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 80, 130, 50));

        btn_pay.setFont(new java.awt.Font("Segoe Print", 1, 24)); // NOI18N
        btn_pay.setText(" Pay");
        btn_pay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_payActionPerformed(evt);
            }
        });
        jPanel6.add(btn_pay, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 130, 50));

        btn_reset.setFont(new java.awt.Font("Segoe Print", 1, 24)); // NOI18N
        btn_reset.setText("Reset");
        btn_reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_resetActionPerformed(evt);
            }
        });
        jPanel6.add(btn_reset, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 20, 130, 50));

        btn_exit.setFont(new java.awt.Font("Segoe Print", 1, 24)); // NOI18N
        btn_exit.setText("Exit");
        btn_exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_exitActionPerformed(evt);
            }
        });
        jPanel6.add(btn_exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, 130, 50));

        btn_print.setFont(new java.awt.Font("Segoe Print", 1, 24)); // NOI18N
        btn_print.setText("Print");
        btn_print.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_printActionPerformed(evt);
            }
        });
        jPanel6.add(btn_print, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 130, 50));

        jPanel3.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 40, 340, 200));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 450, 1290, 250));

        txt_totalreciept.setEditable(false);
        txt_totalreciept.setBackground(new java.awt.Color(204, 204, 204));
        txt_totalreciept.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txt_totalreciept.setText(" ");
        txt_totalreciept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_totalrecieptActionPerformed(evt);
            }
        });
        getContentPane().add(txt_totalreciept, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 400, 240, 30));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Total");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 410, -1, -1));

        txt_vat.setEditable(false);
        txt_vat.setBackground(new java.awt.Color(204, 204, 204));
        txt_vat.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txt_vat.setText(" ");
        txt_vat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_vatActionPerformed(evt);
            }
        });
        getContentPane().add(txt_vat, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 370, 240, 30));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Vat");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 390, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn7ActionPerformed
         String enternumber = txt_cash.getText();
         
         if(enternumber == ""){
         txt_cash.setText(btn7.getText());
         }
         else{
         enternumber = txt_cash.getText() + btn7.getText();
         txt_cash.setText(enternumber);
         }
    }//GEN-LAST:event_btn7ActionPerformed

    private void btn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn8ActionPerformed
        String enternumber = txt_cash.getText();
         
         if(enternumber == ""){
         txt_cash.setText(btn8.getText());
         }
         else{
         enternumber = txt_cash.getText() + btn8.getText();
         txt_cash.setText(enternumber);
         }
    }//GEN-LAST:event_btn8ActionPerformed

    private void btn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn9ActionPerformed
         String enternumber = txt_cash.getText();
         
         if(enternumber == ""){
         txt_cash.setText(btn9.getText());
         }
         else{
         enternumber = txt_cash.getText() + btn9.getText();
         txt_cash.setText(enternumber);
         }
    }//GEN-LAST:event_btn9ActionPerformed

    private void btn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn4ActionPerformed
        String enternumber = txt_cash.getText();
         
         if(enternumber == ""){
         txt_cash.setText(btn4.getText());
         }
         else{
         enternumber = txt_cash.getText() + btn4.getText();
         txt_cash.setText(enternumber);
         }
    }//GEN-LAST:event_btn4ActionPerformed

    private void btn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn5ActionPerformed
        String enternumber = txt_cash.getText();
         
         if(enternumber == ""){
         txt_cash.setText(btn5.getText());
         }
         else{
         enternumber = txt_cash.getText() + btn5.getText();
         txt_cash.setText(enternumber);
         }
    }//GEN-LAST:event_btn5ActionPerformed

    private void btn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn6ActionPerformed
         String enternumber = txt_cash.getText();
         
         if(enternumber == ""){
         txt_cash.setText(btn6.getText());
         }
         else{
         enternumber = txt_cash.getText() + btn6.getText();
         txt_cash.setText(enternumber);
         }
    }//GEN-LAST:event_btn6ActionPerformed

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
        String enternumber = txt_cash.getText();
         
         if(enternumber == ""){
         txt_cash.setText(btn1.getText());
         }
         else{
         enternumber = txt_cash.getText() + btn1.getText();
         txt_cash.setText(enternumber);
         }
    }//GEN-LAST:event_btn1ActionPerformed

    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2ActionPerformed
         String enternumber = txt_cash.getText();
         
         if(enternumber == ""){
         txt_cash.setText(btn2.getText());
         }
         else{
         enternumber = txt_cash.getText() + btn2.getText();
         txt_cash.setText(enternumber);
         }
    }//GEN-LAST:event_btn2ActionPerformed

    private void btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3ActionPerformed
         String enternumber = txt_cash.getText();
         
         if(enternumber == ""){
         txt_cash.setText(btn3.getText());
         }
         else{
         enternumber = txt_cash.getText() + btn3.getText();
         txt_cash.setText(enternumber);
         }
    }//GEN-LAST:event_btn3ActionPerformed

    private void btnzeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnzeroActionPerformed
         String enternumber = txt_cash.getText();
         
         if(enternumber == ""){
         txt_cash.setText(btnzero.getText());
         }
         else{
         enternumber = txt_cash.getText() + btnzero.getText();
         txt_cash.setText(enternumber);
         }
    }//GEN-LAST:event_btnzeroActionPerformed

    private void btn_pointActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_pointActionPerformed
         if (! txt_cash.getText().contains(".")){
         txt_cash.setText(txt_cash.getText() + btn_point.getText()); 
         }
    }//GEN-LAST:event_btn_pointActionPerformed

    private void btn_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clearActionPerformed
        txt_cash.setText("");
        txt_change.setText("");
    }//GEN-LAST:event_btn_clearActionPerformed

    private void btn_burgerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_burgerActionPerformed
         double priceofitem = 5.0;
         DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
         model.addRow(new Object[]{"Burger","1",priceofitem});
         itemCost();
    }//GEN-LAST:event_btn_burgerActionPerformed

    private void btn_pepsiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_pepsiActionPerformed
        double priceofitem = 2.7;
         DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
         model.addRow(new Object[]{"Pepsi","1",priceofitem});
         itemCost();
    }//GEN-LAST:event_btn_pepsiActionPerformed

    private void btn_pizzaleaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_pizzaleaveActionPerformed
        double priceofitem = 25.0;
         DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
         model.addRow(new Object[]{"Pizza with vege","1",priceofitem});
         itemCost();
    }//GEN-LAST:event_btn_pizzaleaveActionPerformed

    private void btn_strawberryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_strawberryActionPerformed
         double priceofitem = 5.0;
         DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
         model.addRow(new Object[]{"Strawberry","1",priceofitem});
         itemCost();
    }//GEN-LAST:event_btn_strawberryActionPerformed

    private void btn_bananaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_bananaActionPerformed
         double priceofitem = 2.5;
         DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
         model.addRow(new Object[]{"Banana","1",priceofitem});
         itemCost();
    }//GEN-LAST:event_btn_bananaActionPerformed

    private void btn_pizzameatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_pizzameatActionPerformed
        double priceofitem = 30.0;
         DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
         model.addRow(new Object[]{"Pizza with Meat","1",priceofitem});
         itemCost();
    }//GEN-LAST:event_btn_pizzameatActionPerformed

    private void btn_appleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_appleActionPerformed
         double priceofitem = 3.5;
         DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
         model.addRow(new Object[]{"Apple","1",priceofitem});
         itemCost();
    }//GEN-LAST:event_btn_appleActionPerformed

    private void btn_meatpieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_meatpieActionPerformed
         double priceofitem = 10.0;
         DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
         model.addRow(new Object[]{"Meat Pie","1",priceofitem});
         itemCost();
    }//GEN-LAST:event_btn_meatpieActionPerformed

    private void btn_jollofActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_jollofActionPerformed
         double priceofitem = 10.0;
         DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
         model.addRow(new Object[]{"Jollof Rice","1",priceofitem});
         itemCost();
    }//GEN-LAST:event_btn_jollofActionPerformed

    private void btn_colaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_colaActionPerformed
         double priceofitem = 2.3;
         DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
         model.addRow(new Object[]{"Cola Drink","1",priceofitem});
         itemCost();
    }//GEN-LAST:event_btn_colaActionPerformed

    private void btn_abachaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_abachaActionPerformed
        double priceofitem = 20.0;
         DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
         model.addRow(new Object[]{"Abacha","1",priceofitem});
         itemCost();
    }//GEN-LAST:event_btn_abachaActionPerformed

    private void btn_burger2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_burger2ActionPerformed
        double priceofitem = 5.0;
         DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
         model.addRow(new Object[]{"Burger meat","1",priceofitem});
         itemCost();
    }//GEN-LAST:event_btn_burger2ActionPerformed

    private void btn_payActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_payActionPerformed
         if(payment_method.getSelectedItem().equals("Cash"))
         {
           Change();
         } else {
            txt_cash.setText("");
            txt_change.setText("");
         
         }
    }//GEN-LAST:event_btn_payActionPerformed

    private void btn_resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_resetActionPerformed
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);
        txt_cash.setText("");
        txt_change.setText("");
        txt_tax.setText("");
        txt_total.setText("");
        txt_subtotal.setText("");
    }//GEN-LAST:event_btn_resetActionPerformed

    private void payment_methodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_payment_methodActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_payment_methodActionPerformed

    private void btn_printActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_printActionPerformed
         MessageFormat header = new MessageFormat("Printing in progress");
         MessageFormat footer = new MessageFormat("Page(0,number, integer)");
         
         try{
          jTable1.print(JTable.PrintMode.NORMAL,header, footer);
         }
         catch(java.awt.print.PrinterException e)
         {
         System.err.format("No Printer Found", e.getMessage());
         }
    }//GEN-LAST:event_btn_printActionPerformed

    private void btn_removeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_removeActionPerformed
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        
        int removeItem = jTable1.getSelectedRow();
         if (removeItem >=0){
         model.removeRow(removeItem);
         }
         itemCost();
         if (payment_method.getSelectedItem().equals("Cash")){
         Change();
         }
         else{
         txt_cash.setText("");
         txt_change.setText("");
         }
    }//GEN-LAST:event_btn_removeActionPerformed
     private JFrame frame;
    private void btn_exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_exitActionPerformed
         frame = new JFrame("Exit");
         //if(JOptionPane.showConfirmDialog(this, frame,"Are you sure u want to exit?", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION){
         int confirm =JOptionPane.showConfirmDialog(this, "Are you sure you want to exit?", "Exit", JOptionPane.YES_NO_OPTION);
         if(confirm==0){
              System.exit(0);
         }
         else{
         
         }
        
        // }
    }//GEN-LAST:event_btn_exitActionPerformed

    private void txt_totalrecieptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_totalrecieptActionPerformed
        
    }//GEN-LAST:event_txt_totalrecieptActionPerformed

    private void txt_vatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_vatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_vatActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JavaSaleAssist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JavaSaleAssist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JavaSaleAssist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JavaSaleAssist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JavaSaleAssist().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JButton btn5;
    private javax.swing.JButton btn6;
    private javax.swing.JButton btn7;
    private javax.swing.JButton btn8;
    private javax.swing.JButton btn9;
    private javax.swing.JButton btn_abacha;
    private javax.swing.JButton btn_apple;
    private javax.swing.JButton btn_banana;
    private javax.swing.JButton btn_burger;
    private javax.swing.JButton btn_burger2;
    private javax.swing.JButton btn_clear;
    private javax.swing.JButton btn_cola;
    private javax.swing.JButton btn_exit;
    private javax.swing.JButton btn_jollof;
    private javax.swing.JButton btn_meatpie;
    private javax.swing.JButton btn_pay;
    private javax.swing.JButton btn_pepsi;
    private javax.swing.JButton btn_pizzaleave;
    private javax.swing.JButton btn_pizzameat;
    private javax.swing.JButton btn_point;
    private javax.swing.JButton btn_print;
    private javax.swing.JButton btn_remove;
    private javax.swing.JButton btn_reset;
    private javax.swing.JButton btn_strawberry;
    private javax.swing.JButton btnzero;
    private javax.swing.JButton jButton49;
    private javax.swing.JButton jButton50;
    private javax.swing.JButton jButton51;
    private javax.swing.JButton jButton52;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JComboBox<String> payment_method;
    private javax.swing.JTextField txt_cash;
    private javax.swing.JTextField txt_change;
    private javax.swing.JTextField txt_subtotal;
    private javax.swing.JTextField txt_tax;
    private javax.swing.JTextField txt_total;
    private javax.swing.JTextField txt_totalreciept;
    private javax.swing.JTextField txt_vat;
    // End of variables declaration//GEN-END:variables
}
